name: auth
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  core:
    path: ../../core
  dartz: ^0.10.1
  equatable: ^2.0.7
  firebase_auth: ^5.5.3
  flutter:
    sdk: flutter
  user:
    path: ../user
  
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
