name: db_firestore
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^5.6.8
  core:
    path: ../../core
  dartz: ^0.10.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
