name: sign_feature
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  auth:
    path: ../../services/auth
  core:
    path: ../../core
  dartz: ^0.10.1
  db_firestore:
    path: ../../services/db_firestore
  design_system:
    path: ../../design_system
  easy_mask: ^2.0.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_modular: ^6.3.4
  user:
    path: ../../services/user

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
    
flutter:
