// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-UnCTtcXSMEnSNRkErwD2grbZAhcCLBs',
    appId: '1:667334835265:web:ec4f269a48da184df5dac0',
    messagingSenderId: '667334835265',
    projectId: 'tokiomarine-vilarinho',
    authDomain: 'tokiomarine-vilarinho.firebaseapp.com',
    storageBucket: 'tokiomarine-vilarinho.firebasestorage.app',
    measurementId: 'G-GMGN92V78C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDppYFaSgtj9wLCjlis6c0QdN0nkgtpBj8',
    appId: '1:667334835265:android:1af51dd3dd489124f5dac0',
    messagingSenderId: '667334835265',
    projectId: 'tokiomarine-vilarinho',
    storageBucket: 'tokiomarine-vilarinho.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABvQOJ5w5C1wcLu-QH_5C8xGpUjJ6ACGA',
    appId: '1:667334835265:ios:12478c30f613ceb2f5dac0',
    messagingSenderId: '667334835265',
    projectId: 'tokiomarine-vilarinho',
    storageBucket: 'tokiomarine-vilarinho.firebasestorage.app',
    iosBundleId: 'com.example.tokioMarineApp',
  );
}
